name: Demo CI

on:
  pull_request:

jobs:

  test:
    name: Run a demo test
    runs-on: ubuntu-latest
    steps:

      - name: main
        run: |
          mkdir -p artifacts
          cat > artifacts/message.md <<EOF
          # Test Message
          
          Note that there are no secrets exposed in this test...
          <details>
          <summary>PR to merge $GITHUB_HEAD_REF $GITHUB_SHA -> $GITHUB_BASE_REF</summary>
          \`\`\`
          $(env | sort)
          \`\`\`
          </details>
          EOF
      - name: Save PR message as artifact
        uses: actions/upload-artifact@v1
        with:
          name: pr_message
          path: artifacts
