# This is a basic workflow to help you get started with Actions

name: add_contributor
    
on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  test:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            This PR is opened by ${{ github.event.pull_request.user.login }} .
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: false # This is the default
