name: add_contributor
    
on:
  push :
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            merges_url: ${{ github.event.push.merges_url }}
            commits_url: ${{ github.event.push.commits_url }}
            git_commits_url: ${{ github.event.push.git_commits_url }}
            comments_url: ${{ github.event.push.comments_url }}
            
          allow-repeats: true
