name: add_contributor
    
on:
  push :
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            This PR is opened by ${{ github.event.push.commits[][author][email] }} .
          allow-repeats: true
